# Generated by Django 3.0.8 on 2021-07-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='postuser',
            name='username',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
